#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tasks_md"
name = "Tasks.md"

description.en = "Markdown file based task management board."

version = "2.3.2~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "mit"

code = "https://github.com/BaldissaraMatheus/Tasks.md"

[integration]
yunohost = '>= 11.2'
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tasks_md"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/BaldissaraMatheus/Tasks.md/archive/refs/tags/2.3.2.tar.gz"
        sha256 = "31ec8172494dd8adbfd25e783ef75c3fc04761e2c5880b6784ebbec3295a7406"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
