#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tasks_md"
name = "Tasks.md"

description.en = "Markdown file based task management board "
description.fr = "Markdown file based task management board "

version = "2.3.2~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "mit"

code = "https://github.com/BaldissaraMatheus/Tasks.md"

[integration]
yunohost = '>= 11.2'
architectures = "all" # TODO : handle the "all" option (no ["all"])
multi_instance = true
ldap = "false" # TODO : fixme, use actual booleans + handle the "not_relevant" value
sso = "true"
# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G... You may have have a look at CI results
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tasks_md"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
        #    ynh_setup_source --dest_dir="$install_dir"
        # You can also define other assets than "main" and add --source_id="foobar" in the previous command
        url = "https://github.com/BaldissaraMatheus/Tasks.md/archive/refs/tags/2.3.2.tar.gz"
        sha256 = "31ec8172494dd8adbfd25e783ef75c3fc04761e2c5880b6784ebbec3295a7406"

        # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
        # to auto-update the previous asset urls and sha256sum + manifest version
        # assuming the upstream's code repo is on github and relies on tags or releases
        # See the 'sources' resource documentation for more details

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
