#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version 0.9.2.1.

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_script_progression --message="Installing NodeJS..." --weight=10

# Install Nodejs
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version
ynh_use_nodejs

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown -R $app: /var/log/$app

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add $app --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding app's configuration file..."

mkdir -p $install_dir/config
ynh_add_config --template=".env" --destination="$install_dir/config/.env"

# FIXME: this should be handled by the core in the future
# You may need to use chmod 600 instead of 400,
# for example if the app is expected to be able to modify its own config
chmod 400 "$install_dir/config"
chown $app:$app "$install_dir/config"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression --message="Installing app..." --weight=5

pushd $install_dir/build
    ynh_exec_as $app $ynh_node_load_PATH $ynh_npm ci
    ynh_exec_as $app $ynh_node_load_PATH $ynh_npm run build
popd

mkdir -p $install_dir/frontend

mv $install_dir/build/dist/. $install_dir/static/
mv $install_dir/static/stylesheets $install_dir

mv $install_dir/build/backend $install_dir

pushd $install_dir/api
    ynh_exec_as $app $ynh_node_load_PATH $ynh_npm ci
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting app's systemd service..."

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last